# Menonaktifkan opsi "Blank Issue" agar semua orang terpaksa menggunakan template yang sudah kita buat
blank_issues_enabled: false

# Memberikan informasi tambahan jika pengguna butuh bantuan di luar pembuatan issue
contact_links:
  - name: Proyek Capstone Support
    url: https://github.com/Cyancyrt/devops-capstone-project/discussions
    about: Gunakan link ini jika kamu ingin bertanya atau berdiskusi sebelum membuat Issue.
